apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Release.Name }}-{{ .Chart.Name }}--sc
  resources:
    requests:
      storage: 5Gi