apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: {{ .Values.names.job }}
spec:
    schedule: "{{ .Values.job.schedule }}"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    - name: {{ .Values.names.containers }}
                      image: {{ .Values.job.image }}
                      imagePullPolicy: Always
                      volumeMounts:
                        - name: azure
                          mountPath: /mnt/azure
                    volumes:
                    - name: azure
                    azureFile:
                        secretName: azure-secret
                        shareName: aksshare
                        readOnly: false
        